# Generated by Django 4.0.2 on 2026-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('institution', models.TextField()),
                ('department', models.TextField()),
                ('utrNo', models.CharField(max_length=20)),
                ('paymentSS', models.URLField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('isPosterPresentation', models.BooleanField(default=False)),
                ('posterURL', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
